### PR TITLE
fix coverage! and improve performance

### LINKED ISSUE #1011: coverage!() errors
using Rasters v0.14.6 coverage!() errors and I'm unable to identify the cause.

load packages and initialize data
```julia
using Rasters
using ArchGDAL
using Shapefile

test_shape_dir = realpath(joinpath(dirname(pathof(Shapefile)), "..", "test", "shapelib_testcases"))
shp_paths = filter(x -> occursin("shp", x), readdir(test_shape_dir; join=true))
shppath = shp_paths[1]
shphandle = Shapefile.Handle(shppath)

lon, lat = X(-179.5:geotile_width:179.5), Y(-89.5:geotile_width:89.5)
ras = Raster(zeros(lon, lat)) 
```

This works
```julia
covsum1 = coverage(sum, shphandle; res=1);
```

This errors
```julia
covsum2 = coverage!(ras, shphandle; mode = sum)
```

Full error trace:
```julia
ERROR: MethodError: no method matching length(::Rasters.Rasterizer{…})
The function `length` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  length(::DataStructures.EnumerateAll)
   @ DataStructures ~/.julia/packages/DataStructures/IrAJn/src/multi_dict.jl:96
  length(::Combinatorics.IntegerPartitions)
   @ Combinatorics ~/.julia/packages/Combinatorics/nV2DW/src/partitions.jl:17
  length(::WeakRefStrings.PosLenString)
   @ WeakRefStrings ~/.julia/packages/WeakRefStrings/31nkb/src/poslenstrings.jl:388
  ...

Stacktrace:
  [1] _similar_shape(itr::Rasters.Rasterizer{…}, ::Base.HasLength)
    @ Base ./array.jl:663
  [2] _collect(cont::UnitRange{…}, itr::Rasters.Rasterizer{…}, ::Base.HasEltype, isz::Base.HasLength)
    @ Base ./array.jl:722
  [3] collect(itr::Rasters.Rasterizer{…})
    @ Base ./array.jl:716
  [4] _get_geometries(data::Rasters.Rasterizer{…}, ::Nothing)
    @ Rasters ~/.julia/packages/Rasters/5ShjB/src/utils.jl:259
  [5] Rasters.Rasterizer(trait::Nothing, data::Rasters.Rasterizer{…}; fill::Float64, geometrycolumn::Nothing, kw::@Kwargs{…})
    @ Rasters ~/.julia/packages/Rasters/5ShjB/src/methods/rasterize.jl:168
  [6] Rasters.Rasterizer(data::Rasters.Rasterizer{…}; fill::Float64, geometrycolumn::Nothing, kw::@Kwargs{…})
    @ Rasters ~/.julia/packages/Rasters/5ShjB/src/methods/rasterize.jl:151
  [7] coverage!(A::Raster{…}, data::Rasters.Rasterizer{…}; scale::Int64, mode::Function, kw::@Kwargs{})
    @ Rasters ~/.julia/packages/Rasters/5ShjB/src/methods/coverage.jl:77
  [8] coverage!(A::Raster{…}, data::Shapefile.Handle{…}; scale::Int64, mode::Function, kw::@Kwargs{})
    @ Rasters ~/.julia/packages/Rasters/5ShjB/src/methods/coverage.jl:78
  [9] coverage!(A::Raster{…}, data::Shapefile.Handle{…})
    @ Rasters ~/.julia/packages/Rasters/5ShjB/src/methods/coverage.jl:75
 [10] top-level scope
    @ ~/Documents/GitHub/GlobalGlacierAnalysis.jl/src/junk.jl.jl:44
Some type information was truncated. Use `show(err)` to see complete types.
```

### LINKED ISSUE #1012: Several orders of magnitude computational gains can be made to `coverage()`
`coverage` is not using the extents of the supplied `geometry` to skip unaffected pixels.

load packages and create test data
```julia
import GeoInterface as GI
using Rasters
using DimensionalData.Dimensions.Lookups
    
# Define the exterior ring of the polygon
res = 0.5

# create global raster for mask coverage calculation
lon, lat = X(Sampled(-180 + res/2:res:180 - res/2, sampling=Intervals(Center()))), Y(Sampled(-90 + res/2:res:90 - res/2, sampling=Intervals(Center())))
ras = Raster(zeros(lon, lat)) 

# create a polygon
exterior_ring = GI.LinearRing([
    (0.0, 0.0),
    (10.0, 0.0),
    (10.0, 10.0),
    (0.0, 10.0),
    (0.0, 0.0) # Closing point
])

polygon0 = [GI.Polygon(exterior_ring)]
```

This takes 7 minutes
```julia
@time covsum1 = coverage(sum, polygon0; to=ras, threaded=false, scale=100);
```

While this takes 2 seconds
```
ras2 = crop(ras; to = polygon0)
@time covsum1 = coverage(sum, polygon0; to=ras2, threaded=false, scale=100);
```

### PR DESCRIPTION
**Pull request by tiemvanderdeure**
Closes #1012 and closes #1011

### CODE REVIEW

File: src/methods/coverage.jl [hunk 1]
```diff
@@ -75,11 +75,13 @@ coverage!(mode::Union{typeof(union),typeof(sum)}, A::AbstractRaster, data; kw...
...
     # We use sum for `reducer` so eltype inference works
     r = Rasterizer(data; reducer=sum, fill=0.0, init=0.0, missingval=0.0, kw...)
-    coverage!(A, r; scale, mode) 
+    _coverage!(A, r; scale, mode) 
 end
 # Collect iterators so threading is easier.
-function _coverage!(A::AbstractRaster, r::Rasterizer; scale::Integer=10, mode=union)  
-    _coverage!(A, GI.trait(r.geom), r.geom, r; scale, mode)
+function _coverage!(A::AbstractRaster, r::Rasterizer; scale::Integer=10, mode=union) 
+    fill!(A, zero(eltype(A)))
```
Comment (asinghvi17) [inline src/methods/coverage.jl:82]: This seems new?

Comment (asinghvi17) [reply src/methods/coverage.jl:82]: is this function run for all geometries only once?  or once per geometry?

Comment (tiemvanderdeure) [reply src/methods/coverage.jl:82]: Just once at the start

Comment (alex-s-gardner) [reply src/methods/coverage.jl:82]: Relevant to this PR but not yet addressed:

these work:
```
coverage(sum, feature; to=ras, threaded=false, scale=100, verbose = false);
coverage(feature; to=ras, threaded=false, scale=100, verbose = false);
```

but mode = `union` returns an error
```
coverage(union, feature; to=ras, threaded=false, scale=100, verbose = false);

UndefVarError: `union` not defined in `Main`
```

Should mode be passed as a symbol ?

**Comment by alex-s-gardner** [comment]
Relevant to this PR but not yet addressed:

these work:
```
coverage(sum, feature; to=ras, threaded=false, scale=100, verbose = false);
coverage(feature; to=ras, threaded=false, scale=100, verbose = false);
```

but mode = `union` returns an error
```
coverage(union, feature; to=ras, threaded=false, scale=100, verbose = false);

UndefVarError: `union` not defined in `Main`
```

Should mode be passed as a symbol ?

**Review by rafaqz — APPROVED** [review]

**Comment by alex-s-gardner** [comment]
Can this be merged?

**Comment by tiemvanderdeure** [comment]
Sorry, forgot about this one a little bit. Should be fixed now
