### PR TITLE
Make sure `open` is always called in aggregate

### LINKED ISSUE #1020: Aggregate does not work with lazy files
Aggregate does not work with lazy files

This errors
```julia
path2geotif = "https://github.com/mommermi/geotiff_sample/raw/refs/heads/master/sample.tif"
ras = Geo.Raster(path2geotif; lazy=true)  # 
greenland_raster = Geo.aggregate(Geo.Rasters.Center(), ras, (Geo.Rasters.Y(2), Geo.Rasters.X(2)))
```

returning
```julia
ERROR: GDALError (CE_Failure, code 10):
        Pointer 'hDS' is NULL in 'GDALGetRasterBand'.


Stacktrace:
  [1] maybe_throw()
    @ GDAL ~/.julia/packages/GDAL/LSxoz/src/error.jl:42
  [2] aftercare
    @ ~/.julia/packages/GDAL/LSxoz/src/error.jl:59 [inlined]
  [3] gdalgetrasterband
    @ ~/.julia/packages/GDAL/LSxoz/src/libgdal.jl:8170 [inlined]
```

The eager version works as expected
```julia
ras = Geo.Raster(path2geotif; lazy=false)  # 
greenland_raster = Geo.aggregate(Geo.Rasters.Center(), ras, (Geo.Rasters.Y(2), Geo.Rasters.X(2)))
```

### PR DESCRIPTION
**Pull request by asinghvi17**
This makes it such that the `src` is first opened and then cached.  Also changed 2 variable names to enhance readability.  The method directly below does the same thing so I think this is reasonable.

Someone should probably add a test.  But at least locally this fixes #1020 for me.

### CODE REVIEW

File: src/methods/aggregate.jl [hunk 1]
```diff
@@ -513,4 +515,4 @@ function _view_disaggregate(A, scale)
     dims_ = disaggregate.((Center(),), dims(A), intscale)
     indices = map((a, i) -> repeat(a; inner=i), axes(A), intscale)
     return rebuild(A; data=view(parent(A), indices...), dims=dims_)
-end
\ No newline at end of file
+end
```
Comment (asinghvi17) [inline src/methods/aggregate.jl:518]: this was completely github's fault, this PR was online only :D

**Comment by alex-s-gardner** [comment]
I made a PR into this branch: https://github.com/rafaqz/Rasters.jl/pull/1022

File: src/methods/aggregate.jl (hunk 1 above)
Comment (rafaqz) [reply src/methods/aggregate.jl:518]: Microsoft adding their awful line endings

**Review by rafaqz — APPROVED** [review]
